<a href="https://colab.research.google.com/github/Ristoll/AIS_L4-6/blob/main/LR_4_task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import preprocessing
input_data = np.array([[1.6, 3.1, 6.5],
                       [-4.9, -2.2, 1.3],
                       [2.2, 6.5, -6.1],
                       [-3.4, 5.2, -3.2]])
#Binarization
data_binarized = preprocessing.Binarizer(threshold = 2.1).fit_transform(input_data)
print("\n Binarized data:\n", data_binarized)

#Mean and standard deviation
print("\n BEFORE: ")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

#Exclusion of the average
data_scaled = preprocessing.scale(input_data)
print("\n AFTER:")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))

#MinMax scaling
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\n Min max scaled data:\n", data_scaled_minmax)

#Normalization
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nl1 normalized data:\n", data_normalized_l1)
print("\nl2 normalized data:\n", data_normalized_l2)


 Binarized data:
 [[0. 1. 1.]
 [0. 0. 0.]
 [1. 1. 0.]
 [0. 1. 0.]]

 BEFORE: 
Mean = [-1.125  3.15  -0.375]
Std deviation = [3.07845335 3.3185087  4.76517313]

 AFTER:
Mean = [ 0.00000000e+00 -1.38777878e-16  2.77555756e-17]
Std deviation = [1. 1. 1.]

 Min max scaled data:
 [[0.91549296 0.6091954  1.        ]
 [0.         0.         0.58730159]
 [1.         1.         0.        ]
 [0.21126761 0.85057471 0.23015873]]

l1 normalized data:
 [[ 0.14285714  0.27678571  0.58035714]
 [-0.58333333 -0.26190476  0.1547619 ]
 [ 0.14864865  0.43918919 -0.41216216]
 [-0.28813559  0.44067797 -0.27118644]]

l2 normalized data:
 [[ 0.21689059  0.42022552  0.88111803]
 [-0.88666908 -0.39809632  0.23523874]
 [ 0.23961218  0.70794508 -0.66437923]
 [-0.48650924  0.74407295 -0.45789105]]
